"""usernames and platform operator

Revision ID: 3a59d664df20
Revises: bbcbbd0ad2ca
Create Date: 2026-09-02 07:47:27.648932
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3a59d664df20'
down_revision = 'bbcbbd0ad2ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=True))
    # Autogenerate produced a bare NOT NULL column, which cannot be added
    # to a table that already has rows. Existing accounts are ordinary
    # users; the default is dropped afterwards so the application stays
    # the only thing that decides what a new row contains.
    op.add_column(
        'users',
        sa.Column('is_superadmin', sa.Boolean(), nullable=False,
                  server_default=sa.false()),
    )
    op.alter_column('users', 'is_superadmin', server_default=None)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'is_superadmin')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
