"""metric fields

Revision ID: 527ae14c3697
Revises: 8236eb15e7e4
Create Date: 2026-09-06 23:11:13.095210
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '527ae14c3697'
down_revision = '8236eb15e7e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('short_label', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('numerator', sa.String(length=80), nullable=False),
    sa.Column('denominator', sa.String(length=80), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_metric_field_org_key')
    )
    op.create_index('ix_metric_fields_org_position', 'metric_fields', ['org_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_fields_org_position', table_name='metric_fields')
    op.drop_table('metric_fields')
    # ### end Alembic commands ###
