"""operator sessions belong nowhere

Revision ID: 8236eb15e7e4
Revises: 3a59d664df20
Create Date: 2026-09-02 07:50:55.576582
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8236eb15e7e4'
down_revision = '3a59d664df20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
